### ISSUE TITLE
We have to upgrade quarkus when it gets log4j integration fixed (reported on quarkus side as #11644)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxauth-config#165]
We have log4j used all over different projects including oxauth. Many oxauth beans can be re-used in oxauth-config api but `log4j` issue blocks such integration which leads to ugly code duplication:

Reported on quarkus side here:
https://github.com/quarkusio/quarkus/issues/11644

On our side it looks as 
```
13:54:31 ERROR [io.qu.ve.ht.ru.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /api/v1/oxauth/config/jwks failed, error id: 9fd6986c-b04b-4054-922a-bf92a8230423-1: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalAccessError: failed to access class org.apache.logging.log4j.util.StackLocator$FqcnCallerLocator from class org.apache.logging.log4j.util.StackLocator (org.apache.logging.log4j.util.StackLocator$FqcnCallerLocator is in unnamed module of loader 'app'; org.apache.logging.log4j.util.StackLocator is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4b2bac3f)
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:132)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.IllegalAccessError: failed to access class org.apache.logging.log4j.util.StackLocator$FqcnCallerLocator from class org.apache.logging.log4j.util.StackLocator (org.apache.logging.log4j.util.StackLocator$FqcnCallerLocator is in unnamed module of loader 'app'; org.apache.logging.log4j.util.StackLocator is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @4b2bac3f)
	at org.apache.logging.log4j.util.StackLocator.<clinit>(StackLocator.java:37)
	at org.apache.logging.log4j.util.StackLocatorUtil.<clinit>(StackLocatorUtil.java:33)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:133)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:118)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:148)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:307)
	at org.apache.log4j.Logger$PrivateManager.getContext(Logger.java:59)
	at org.apache.log4j.Logger.getLogger(Logger.java:41)
	at org.gluu.oxauth.model.util.Util.<clinit>(Util.java:39)
	at org.gluu.oxauth.model.jwk.JSONWebKey.toJSONObject(JSONWebKey.java:220)
	at org.gluu.oxauth.model.jwk.JSONWebKeySet.toJSONObject(JSONWebKeySet.java:87)
	at org.gluu.oxauth.model.jwk.JSONWebKeySet.toString(JSONWebKeySet.java:99)
	at org.gluu.configapi.rest.resource.JwksResource.get(JwksResource.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:638)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:504)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:454)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:456)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:417)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	... 20 more
```

**Comment by syntrydy** [comment]
@yuriyz i think Quarkus already support log4j

**Comment by syntrydy** [comment]
https://quarkus.io/guides/logging#what-about-apache-log4j

**Comment by yuriyz** [comment]
@syntrydy you misunderstood issue. It's not to support log4j, it's about exception which quarkus triggers when it's accessing classes (in our cases oxauth classes from model) that are using log4j.

**Comment by yuriyz** [comment]
@syntrydy check exception in description `at org.gluu.oxauth.model.jwk.JSONWebKey.toJSONObject(JSONWebKey.java:220)`.

**Comment by yuriyz** [comment]
Found solution, 2 things has to be made:
1. add dependency
```
  <dependency>
      <groupId>org.jboss.logmanager</groupId>
      <artifactId>log4j2-jboss-logmanager</artifactId> 
    </dependency>
```
2. add exclusion to all dependencies that has resteasy as cross dependency
```
<exclusions>
                <exclusion>
                    <groupId>org.jboss.resteasy</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
```
